# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
name:             Themeblr
description:      A powerful CSS framework boilerplate and Bootstrap 4 themes builder
baseurl:
encoding:         UTF-8

gems:
  - jekyll-sitemap

# Custom vars
current_version:  1.0.1
repo:             https://github.com/websemantics/themeblr
